

services:
  postgres:
    container_name: marketplace-api
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marketplace
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres